USE master
GO

-----Create OrderDB database
IF NOT EXISTS (SELECT 1 FROM sys.databases WHERE name = N'OrderDB')
BEGIN
CREATE DATABASE [OrderDB] ON  PRIMARY 
( NAME = N'OrderDB', FILENAME = N'C:\MSSQL\DATA\OrderDB.mdf' , SIZE = 100MB , MAXSIZE = UNLIMITED , FILEGROWTH = 20), 
 FILEGROUP [INDEX_DATA] 
( NAME = N'OrderDB_Index', FILENAME = N'C:\MSSQL\INDEX\OrderDB.ndf' , SIZE = 100MB , MAXSIZE = UNLIMITED , FILEGROWTH = 20)
 LOG ON 
( NAME = N'OrderDB_Log', FILENAME = N'C:\MSSQL\LOG\OrderDB.ldf' , SIZE = 100MB , MAXSIZE = UNLIMITED , FILEGROWTH = 20)
END
GO




